model_params:
  input_features:
  output_features: 10
  to_validate: True
  batch_size: 100
  keywithseqvals : [1,2,3,hello,"deepak"]
  boolFlag: False

hyperparameters:
  learning_rate: 0.0001
  epochs: 1000

project_params:
  model_save_location:
  

logging:
  filename: self_training_mnist.log #optional and defaults to log.log
  level: "DEBUG" #optional and defaults to DEBUG
  format: "%(levelname)s:%(filename)s:%(message)s at line %(lineno)s"
  #format: "%(asctime)s:%(levelname)s:%(filename)s:%(message)s at line %(lineno)s"